#
# SPDX-FileCopyrightText: 2024 Georg Kunz <der.schorsch@gmail.com>
# SPDX-License-Identifier: MIT
#
name: Run unit tests

on:
  pull_request: null

permissions: read-all

jobs:
  tests:
    permissions:
      contents: read
      packages: read
      statuses: write

    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: python3 -m pip install .
    - name: Run unit tests
      run: |
        pushd tests
        python3 unit_tests.py
